"""add_description_to_items

Revision ID: c2075c1633c3
Revises: 61bcb9d189d3
Create Date: 2026-04-01 19:45:37.796843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2075c1633c3'
down_revision: Union[str, Sequence[str], None] = '61bcb9d189d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_items', sa.Column('description', sa.String(), nullable=True))
    op.add_column('quote_items', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quote_items', 'description')
    op.drop_column('invoice_items', 'description')
    # ### end Alembic commands ###
